name: deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: NCP login and after git pull, docker compose up --build
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.NCP_HOST}}
          username: ${{secrets.NCP_USERNAME}}
          password: ${{secrets.NCP_PASSWORD}}
          port: ${{secrets.NCP_PORT}}
          script: |
            cd /root/pdf_chatbot
            docker-compose down
            git pull origin main
            docker-compose up -d