name: deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update DNS settings
        run: |
          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
          echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf > /dev/null
          
      - name: NCP login and after git pull, docker compose up --build
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.NCP_HOST}}
          username: ${{secrets.NCP_USERNAME}}
          password: ${{secrets.NCP_PASSWORD}}
          port: ${{secrets.NCP_PORT}}
          script: |
            cd /root/pdf_chatbot
            ^C
            git pull origin main
            uvicorn main:app --reload
            